-- Loading the csv file  data into our staging table

INSERT INTO STG_SUPERSTORE(
LOAD_BATCH_ID, ROW_ID,
ORDER_ID, ORDER_DATE, SHIP_DATE, SHIP_MODE, 
CUSTOMER_ID, CUSTOMER_NAME, SEGMENT, 
COUNTRY, CITY, STATE_PROVINCE, POSTAL_CODE, REGION,
PRODUCT_ID, CATEGORY, SUB_CATEGORY, PRODUCT_NAME,
SALES, QUANTITY, DISCOUNT, PROFIT, RETURNED

)
SELECT LOAD_BATCH_ID, ROW_ID,
ORDER_ID, ORDER_DATE, SHIP_DATE, SHIP_MODE, 
CUSTOMER_ID, CUSTOMER_NAME, SEGMENT, 
COUNTRY, CITY, STATE_PROVINCE, POSTAL_CODE, REGION,
PRODUCT_ID, CATEGORY, SUB_CATEGORY, PRODUCT_NAME,
SALES, QUANTITY, DISCOUNT, PROFIT, RETURNED
FROM STG_SUPERSTORE_2K;


