-- Superstore ops hub
-- creating the staging table stg_superstore

CREATE TABLE stg_superstore(
    LOAD_BATCH_ID NUMBER(10) DEFAULT 1 NOT NULL, 
    ROW_ID NUMBER(10) NOT NULL,
    
    ORDER_ID VARCHAR2(20) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    SHIP_DATE DATE,
    SHIP_MODE VARCHAR2(30),

    CUSTOMER_ID VARCHAR2(20) NOT NULL,
    CUSTOMER_NAME VARCHAR2(80) NOT NULL,
    SEGMENT VARCHAR2(30),

    COUNTRY VARCHAR2(50),
    CITY VARCHAR2(50),
    STATE_PROVINCE VARCHAR2(50),
    POSTAL_CODE VARCHAR2(20),
    REGION VARCHAR2(20),

    PRODUCT_ID VARCHAR2(30) NOT NULL,
    CATEGORY VARCHAR2(30),
    SUB_CATEGORY VARCHAR2(30),
    PRODUCT_NAME VARCHAR2(200) NOT NULL,

    SALES NUMBER(12, 4) NOT NULL, 
    QUANTITY NUMBER(8) NOT NULL, 
    DISCOUNT NUMBER(5, 2), 
    PROFIT NUMBER(12, 4), 
    RETURNED VARCHAR2(5),
    LOADED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_stg_superstore PRIMARY KEY (LOAD_BATCH_ID, ROW_ID),
    CONSTRAINT chk_stg_quantity CHECK (QUANTITY > 0),
    CONSTRAINT chk_stg_discount CHECK (DISCOUNT IS NULL OR (DISCOUNT >=0 AND DISCOUNT <=1))
);

